[workspace]

members = [
    "builder",
    "pool",
    "shared",
    "convert",
    "timer",
    "uuid",
    "merge",
    "aio",
    "merge_derive",
    "dawg",
    "collections",
    "url",
    "email",
    "verify",
    "time"
]
