[package]
name = "uuid"
version = "0.1.0"
authors = ["Alex Sarapulov <1molyee@gmail.com>"]
edition = "2018"
publish = false

[features]
default = ["v1", "v4"]
v1 = []
v4 = ["rand/pcg128"]

[dependencies]
rand = { path = "../rand", optional = true }
convert = { path = "../convert" }
