[package]
name = "merge_derive"
version = "0.1.0"
authors = ["Alex Sarapulov <1molyee@gmail.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = "0.15.34"
quote = "0.6.0"
proc-macro2 = "0.4.4"